# Default values for your projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ghcr.io/salaboy/fmtok8s-c4p-service
  tag: v0.0.1-native
  pullPolicy: Always

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true

prometheus:
  enabled: true
  
# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knative:
  # You can add traffic rules here to customize the Knative Serving rules
  enabled: false
#  traffic:
#  - latestRevision: false
#    percent: 50
#    revisionName: fmtok8s-c4p-00001
#  - latestRevision: true
#    percent: 50

service:
  name: fmtok8s-c4p
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:

resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "0.1"
    memory: 256Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: ""
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: ""